name: Skills Utilization CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Backend Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/skills-utilization:latest \
            ./code

      - name: Push Backend Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/skills-utilization:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Stop containers
        working-directory: ./code
        run: |
          docker compose down

      - name: Pull latest image
        working-directory: ./code
        run: |
          docker compose pull

      - name: Start containers
        working-directory: ./code
        run: |
          docker compose up -d
